name: main-Sync-Manual 

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_ssh_private_key: ${{ secrets.MAIN_SECRET }}
          source_repo: "git@github.com:RoopeshCheruvathur/magento_docker.git"
          source_branch: "main"
          destination_ssh_private_key : ${{ secrets.MAIN_SECRET }}
          destination_repo: "git@github.com:RoopeshCheruvathur/magento_docker_temp.git"
          destination_branch: "main"
